### ISSUE TITLE
【功能建议】能否支持go的包模式，方便在其他流程中嵌入quake

### ISSUE THREAD

**Issue by ghost** [360quake/quake_go#10]
如题，支持后就不用导出后再解析文件了

**Comment by rootphantomer** [comment]
好的，我研究下

**Comment by rootphantomer** [comment]
[](https://github.com/360quake/quake_go/releases/tag/v2.0) v2.0已经支持，用法可以看下readme。也可以参考这个第三方项目的package（<https://github.com/jinycoo/go-quake>）
