### ISSUE TITLE
seach语句中的空格被吃掉

### ISSUE THREAD

**Issue by ghost** [360quake/quake_go#14]
问题如图所示：

![image](https://user-images.githubusercontent.com/43143519/193444595-33df6a17-5de3-43c9-8b71-2c6b3d267876.png)

[在这里](https://github.com/360quake/quake_go/blob/5e5d449daa88d69ff2b88bcd3e17f2d922dabcd7/utils/api.go#L53)把空字符替换掉了，建议加以更健壮的判断

**Comment by rootphantomer** [comment]
fix https://github.com/360quake/quake_go/commit/5591abbabc2bb728624b526816678401ce76a2b3

**Comment by rootphantomer** [comment]
暂时把替换空格的代码注释了
